# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scratch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit

import Google_News_Scrapper
import HeatMap
from SentimentAnalysis import SentimentAnalysis

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(60, 220, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 170, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Widget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 270, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(Widget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 100, 381, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(60, 80, 91, 61))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Widget)
        self.textEdit.setGeometry(QtCore.QRect(233, 130, 371, 161))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton.setText(_translate("Widget", "HEAT MAP"))
        self.pushButton_2.setText(_translate("Widget", "DATA"))
        self.pushButton_3.setText(_translate("Widget", "SUMMARY"))
        self.label.setText(_translate("Widget", "ENTER TICKER"))

        self.lineEdit.editingFinished.connect(self.edit_line)
        self.pushButton.clicked.connect(self.show_stats)
        self.pushButton.clicked.connect(self.heat_map)
        self.pushButton_3.clicked.connect(self.summary)

    def edit_line(self):
        # print(self.lineEdit.text())
        enter_ticker = self.lineEdit.text()
        self.summary(enter_ticker)

    @classmethod
    def show_stats(cls):
        print("Stats")

    @classmethod
    def heat_map(cls):
        heat = HeatMap.show_heat_map()

    def summary(self, ticker):
        company_articles = Google_News_Scrapper.ScrapeArticles(ticker, '08/01/2021', '8/07/2021')
        sentiment = SentimentAnalysis()
        sentiment.lexical_article_analyze(company_articles.search_articles()[0][0:5])
        self.textEdit.clear()
        self.textEdit.insertPlainText(sentiment.summary[1])
        print("34")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
